server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/DemoTest
    username: test
    password: test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /demo.html
    operations-sorter: method
    enabled: true
